# Generated by Django 4.2 on 2023-07-07 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0003_bildirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
