# Generated by Django 4.2 on 2023-07-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0004_alter_warehouseinputdata_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
