# Generated by Django 4.2 on 2023-07-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0005_alter_warehouseinputdata_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseinputdata',
            old_name='ort_rulot_doluluğu',
            new_name='ort_rulot_dolulugu',
        ),
    ]
