# Generated by Django 4.2 on 2023-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0006_rename_ort_rulot_doluluğu_warehouseinputdata_ort_rulot_dolulugu'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinputdata',
            name='report_month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='warehouseinputdata',
            name='report_year',
            field=models.IntegerField(default=2023),
        ),
    ]
