# Generated by Django 4.2 on 2023-07-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0008_alter_warehouseinputdata_report_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseinputdata',
            name='tarih',
        ),
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='report_month',
            field=models.CharField(choices=[('1', 'Ocak'), ('2', 'Şubat'), ('3', 'Mart'), ('4', 'Nisan'), ('5', 'Mayıs'), ('6', 'Haziran'), ('7', 'Temmuz'), ('8', 'Ağustos'), ('9', 'Eylül'), ('10', 'Ekim'), ('11', 'Kasım'), ('12', 'Aralık')], default=7, max_length=2),
        ),
    ]
