# Generated by Django 4.2 on 2023-07-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0009_remove_warehouseinputdata_tarih_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseinputdata',
            old_name='gerceklesen_km_sehidısı',
            new_name='gerceklesen_km_sehirdisi',
        ),
        migrations.RenameField(
            model_name='warehouseinputdata',
            old_name='rulot_maaliyeti_sehirdısı',
            new_name='rulot_maaliyeti_sehirdisi',
        ),
        migrations.RenameField(
            model_name='warehouseinputdata',
            old_name='rulot_sayisi_sehirdısı',
            new_name='rulot_sayisi_sehirdisi',
        ),
        migrations.RenameField(
            model_name='warehouseinputdata',
            old_name='sefer_maaliyeti_sehirdısı',
            new_name='sefer_maaliyeti_sehirdisi',
        ),
        migrations.RenameField(
            model_name='warehouseinputdata',
            old_name='sefer_sayisi_sehirdısı',
            new_name='sefer_sayisi_sehirdisi',
        ),
    ]
