# Generated by Django 4.2 on 2023-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0010_rename_gerceklesen_km_sehidısı_warehouseinputdata_gerceklesen_km_sehirdisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='gorulme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bildirim',
            name='metin',
            field=models.TextField(),
        ),
    ]
