# Generated by Django 4.2 on 2023-07-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depolar', '0011_bildirim_gorulme_tarihi_alter_bildirim_metin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='koli_rulot_doluluk',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='ms_rulot_doluluk',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='ort_rulot_dolulugu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='taze_rulot_doluluk',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
