# Generated by Django 4.2 on 2023-08-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('depolar', '0012_bildirim_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bildirim',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseinputdata',
            name='report_month',
            field=models.CharField(choices=[('1', 'Ocak'), ('2', 'Şubat'), ('3', 'Mart'), ('4', 'Nisan'), ('5', 'Mayıs'), ('6', 'Haziran'), ('7', 'Temmuz'), ('8', 'Ağustos'), ('9', 'Eylül'), ('10', 'Ekim'), ('11', 'Kasım'), ('12', 'Aralık')], default=8, max_length=2),
        ),
    ]
