# Generated by Django 4.2 on 2023-08-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filotakip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filodataentry',
            name='month_select',
        ),
        migrations.RemoveField(
            model_name='filodataentry',
            name='year_select',
        ),
        migrations.AddField(
            model_name='filodataentry',
            name='report_month',
            field=models.CharField(choices=[('1', 'Ocak'), ('2', 'Şubat'), ('3', 'Mart'), ('4', 'Nisan'), ('5', 'Mayıs'), ('6', 'Haziran'), ('7', 'Temmuz'), ('8', 'Ağustos'), ('9', 'Eylül'), ('10', 'Ekim'), ('11', 'Kasım'), ('12', 'Aralık')], default=8, max_length=2),
        ),
        migrations.AddField(
            model_name='filodataentry',
            name='report_year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044'), ('2045', '2045'), ('2046', '2046'), ('2047', '2047'), ('2048', '2048'), ('2049', '2049'), ('2050', '2050')], default=2023, max_length=4),
        ),
    ]
