# Generated by Django 4.2 on 2023-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filotakip', '0002_remove_filodataentry_month_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filodataentry',
            name='mevcut',
            field=models.CharField(choices=[('MarnaK', 'MARNAK'), ('Murat', 'MURAT'), ('Bir', 'BİR'), ('Ceva', 'CEVA'), ('Netlog', 'NETLOG'), ('Deneme1', 'DENEME1'), ('Deneme2', 'DENEME2'), ('Deneme3', 'DENEME3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='filodataentry',
            name='sezon',
            field=models.CharField(choices=[('MarnaK', 'MARNAK'), ('Murat', 'MURAT'), ('Bir', 'BİR'), ('Ceva', 'CEVA'), ('Netlog', 'NETLOG'), ('Deneme1', 'DENEME1'), ('Deneme2', 'DENEME2'), ('Deneme3', 'DENEME3')], max_length=10),
        ),
    ]
