# Generated by Django 4.2 on 2023-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filotakip', '0003_alter_filodataentry_mevcut_alter_filodataentry_sezon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filodataentry',
            name='mevcut',
            field=models.CharField(choices=[('MarnaK', 'MARNAK'), ('Murat', 'MURAT'), ('Bir', 'BİR'), ('Ceva', 'CEVA'), ('Netlog', 'NETLOG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='filodataentry',
            name='sezon',
            field=models.CharField(choices=[('MarnaK', 'MARNAK'), ('Murat', 'MURAT'), ('Bir', 'BİR'), ('Ceva', 'CEVA'), ('Netlog', 'NETLOG')], max_length=10),
        ),
    ]
